<?php

return [
    [
        'name' => 'Auckland Plumbing Experts',
        'industry' => 'Construction & Trades',
        'category' => 'Plumbing',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Mt Eden', 'Newmarket', 'Ponsonby', 'North Shore'],
        'description' => 'Licensed plumbers for leak repairs, hot water cylinders, blocked drains, bathroom plumbing, and urgent call-outs.',
        'services' => ['Leak repairs', 'Blocked drains', 'Hot water cylinders', 'Bathroom plumbing', 'Emergency plumbing'],
        'tags' => ['plumber', 'plumbing', 'drainage', 'pipe repair', 'hot water'],
        'phone' => '021 456 789',
        'email' => 'plumbing@example.com',
        'rating' => 4.8,
        'jobs_completed' => 214,
        'response_time' => 'Usually replies within 2 hours',
    ],
    [
        'name' => 'North Shore Drainage & Plumbing',
        'industry' => 'Construction & Trades',
        'category' => 'Plumbing',
        'location' => 'Auckland',
        'service_areas' => ['Albany', 'Takapuna', 'Glenfield', 'Browns Bay', 'Auckland'],
        'description' => 'Drain unblocking, sewer repairs, water mains, bathroom fit-offs, and small plumbing maintenance jobs.',
        'services' => ['Drain unblocking', 'Sewer repairs', 'Water mains', 'Bathroom fit-off'],
        'tags' => ['drain', 'blocked toilet', 'sewer', 'water leak'],
        'phone' => '020 333 1144',
        'email' => 'northshore.plumbing@example.com',
        'rating' => 4.6,
        'jobs_completed' => 137,
        'response_time' => 'Usually replies same day',
    ],
    [
        'name' => 'Kiwi Electrical Solutions',
        'industry' => 'Construction & Trades',
        'category' => 'Electrical',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Manukau', 'Henderson', 'Papakura', 'North Shore'],
        'description' => 'Registered electricians for residential and commercial electrical repairs, wiring, switchboards, lighting, and safety checks.',
        'services' => ['Electrical repairs', 'Lighting installation', 'Switchboard upgrades', 'Safety inspections', 'New wiring'],
        'tags' => ['electrician', 'electrical', 'lights', 'wiring', 'switchboard'],
        'phone' => '022 333 444',
        'email' => 'electrical@example.com',
        'rating' => 4.9,
        'jobs_completed' => 301,
        'response_time' => 'Usually replies within 1 hour',
    ],
    [
        'name' => 'Wellington Power Pros',
        'industry' => 'Construction & Trades',
        'category' => 'Electrical',
        'location' => 'Wellington',
        'service_areas' => ['Wellington Central', 'Lower Hutt', 'Porirua', 'Petone'],
        'description' => 'Electrical troubleshooting, new installations, EV charger wiring, office fit-outs, and compliance checks.',
        'services' => ['EV charger installation', 'Office fit-outs', 'Fault finding', 'Compliance checks'],
        'tags' => ['electrician', 'ev charger', 'commercial electrical', 'fault finding'],
        'phone' => '021 448 930',
        'email' => 'wellington.power@example.com',
        'rating' => 4.7,
        'jobs_completed' => 166,
        'response_time' => 'Usually replies same day',
    ],
    [
        'name' => 'North Shore Builders',
        'industry' => 'Construction & Trades',
        'category' => 'Renovations',
        'location' => 'Auckland',
        'service_areas' => ['North Shore', 'Albany', 'Takapuna', 'Devonport', 'Auckland'],
        'description' => 'Home renovations, extensions, decks, pergolas, repairs, and general building work for Auckland homeowners.',
        'services' => ['Home renovations', 'Deck building', 'Extensions', 'General repairs', 'Pergolas'],
        'tags' => ['builder', 'building', 'renovation', 'deck', 'extension'],
        'phone' => '020 111 222',
        'email' => 'builders@example.com',
        'rating' => 4.8,
        'jobs_completed' => 89,
        'response_time' => 'Usually replies within 4 hours',
    ],
    [
        'name' => 'Hamilton Renovation Group',
        'industry' => 'Construction & Trades',
        'category' => 'Renovations',
        'location' => 'Hamilton',
        'service_areas' => ['Hamilton', 'Cambridge', 'Te Awamutu', 'Morrinsville'],
        'description' => 'Kitchen renovations, bathroom upgrades, small extensions, and rental property repair projects.',
        'services' => ['Kitchen renovations', 'Bathroom upgrades', 'Small extensions', 'Rental repairs'],
        'tags' => ['builder', 'renovation', 'kitchen', 'bathroom', 'rental'],
        'phone' => '027 245 6677',
        'email' => 'hamilton.reno@example.com',
        'rating' => 4.5,
        'jobs_completed' => 73,
        'response_time' => 'Usually replies next business day',
    ],
    [
        'name' => 'Harbour Painting & Decorating',
        'industry' => 'Construction & Trades',
        'category' => 'Painting',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Parnell', 'Remuera', 'Mt Roskill', 'North Shore'],
        'description' => 'Interior and exterior painting, plaster touch-ups, colour consultation, rental repainting, and fence staining.',
        'services' => ['Interior painting', 'Exterior painting', 'Plaster repairs', 'Fence staining', 'Rental repainting'],
        'tags' => ['painter', 'painting', 'decorating', 'plaster', 'staining'],
        'phone' => '021 884 210',
        'email' => 'harbour.paint@example.com',
        'rating' => 4.7,
        'jobs_completed' => 142,
        'response_time' => 'Usually replies same day',
    ],
    [
        'name' => 'Tauranga Tiling Pros',
        'industry' => 'Construction & Trades',
        'category' => 'Tiling',
        'location' => 'Tauranga',
        'service_areas' => ['Tauranga', 'Mount Maunganui', 'Papamoa', 'Bethlehem'],
        'description' => 'Bathroom tiles, kitchen splashbacks, waterproofing coordination, floor tiles, and repair work.',
        'services' => ['Bathroom tiling', 'Kitchen splashbacks', 'Floor tiling', 'Tile repairs'],
        'tags' => ['tiler', 'tiling', 'bathroom', 'splashback', 'waterproofing'],
        'phone' => '022 331 909',
        'email' => 'tauranga.tiling@example.com',
        'rating' => 4.6,
        'jobs_completed' => 58,
        'response_time' => 'Usually replies within 6 hours',
    ],
    [
        'name' => 'Wellington Roofing Co',
        'industry' => 'Construction & Trades',
        'category' => 'Roofing',
        'location' => 'Wellington',
        'service_areas' => ['Wellington', 'Lower Hutt', 'Upper Hutt', 'Kapiti'],
        'description' => 'Roof leak repairs, re-roofing, gutter replacement, roof maintenance, and storm damage checks.',
        'services' => ['Roof leak repairs', 'Re-roofing', 'Gutter replacement', 'Roof maintenance'],
        'tags' => ['roofer', 'roofing', 'roof leak', 'gutter', 'storm damage'],
        'phone' => '027 600 391',
        'email' => 'wellington.roofing@example.com',
        'rating' => 4.7,
        'jobs_completed' => 121,
        'response_time' => 'Usually replies same day',
    ],
    [
        'name' => 'Sparkle Home Cleaning',
        'industry' => 'Home Services',
        'category' => 'Home Cleaning',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Mt Eden', 'Epsom', 'New Lynn', 'North Shore'],
        'description' => 'Regular home cleaning, end-of-tenancy cleaning, move-out cleaning, and one-off deep cleaning.',
        'services' => ['Weekly cleaning', 'Deep cleaning', 'Move-out cleaning', 'End-of-tenancy cleaning'],
        'tags' => ['cleaner', 'cleaning', 'house cleaning', 'end of tenancy', 'move out'],
        'phone' => '021 234 567',
        'email' => 'cleaning@example.com',
        'rating' => 4.9,
        'jobs_completed' => 254,
        'response_time' => 'Usually replies within 1 hour',
    ],
    [
        'name' => 'Christchurch Clean Team',
        'industry' => 'Home Services',
        'category' => 'Home Cleaning',
        'location' => 'Christchurch',
        'service_areas' => ['Christchurch', 'Riccarton', 'Hornby', 'Papanui', 'Sumner'],
        'description' => 'Home cleaning, office cleaning, carpet spot cleaning, and spring cleaning packages.',
        'services' => ['Home cleaning', 'Office cleaning', 'Spring cleaning', 'Carpet spot cleaning'],
        'tags' => ['cleaner', 'office cleaning', 'spring clean', 'carpet'],
        'phone' => '020 882 119',
        'email' => 'christchurch.clean@example.com',
        'rating' => 4.5,
        'jobs_completed' => 92,
        'response_time' => 'Usually replies same day',
    ],
    [
        'name' => 'Dunedin Secure Locksmiths',
        'industry' => 'Home Services',
        'category' => 'Locksmith',
        'location' => 'Dunedin',
        'service_areas' => ['Dunedin', 'Mosgiel', 'Port Chalmers'],
        'description' => 'Emergency lockouts, lock replacement, re-keying, window locks, and rental property lock changes.',
        'services' => ['Emergency lockouts', 'Lock replacement', 'Re-keying', 'Window locks'],
        'tags' => ['locksmith', 'locks', 'keys', 'emergency lockout'],
        'phone' => '027 830 114',
        'email' => 'dunedin.lock@example.com',
        'rating' => 4.6,
        'jobs_completed' => 78,
        'response_time' => 'Usually replies within 2 hours',
    ],
    [
        'name' => 'City Auto Garage',
        'industry' => 'Automotive',
        'category' => 'Mechanics',
        'location' => 'Christchurch',
        'service_areas' => ['Christchurch', 'Riccarton', 'Linwood', 'Sydenham'],
        'description' => 'Vehicle servicing, diagnostics, brakes, tyres, WOF preparation, and mechanical repairs.',
        'services' => ['Car servicing', 'Diagnostics', 'Brake repairs', 'Tyre services', 'WOF checks'],
        'tags' => ['mechanic', 'car service', 'brakes', 'tyres', 'wof'],
        'phone' => '027 555 888',
        'email' => 'auto@example.com',
        'rating' => 4.4,
        'jobs_completed' => 187,
        'response_time' => 'Usually replies same day',
    ],
    [
        'name' => 'Auckland Auto Electrical',
        'industry' => 'Automotive',
        'category' => 'Auto Electrical',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Manukau', 'Henderson', 'Onehunga'],
        'description' => 'Battery issues, alternators, starter motors, vehicle wiring, lights, and diagnostic fault scanning.',
        'services' => ['Battery testing', 'Alternator repairs', 'Starter motors', 'Vehicle diagnostics'],
        'tags' => ['auto electrician', 'battery', 'alternator', 'starter motor', 'diagnostic'],
        'phone' => '021 778 443',
        'email' => 'auto.electrical@example.com',
        'rating' => 4.6,
        'jobs_completed' => 119,
        'response_time' => 'Usually replies within 3 hours',
    ],
    [
        'name' => 'Glow Beauty Studio',
        'industry' => 'Beauty & Wellness',
        'category' => 'Beauty Clinics',
        'location' => 'Hamilton',
        'service_areas' => ['Hamilton', 'Chartwell', 'Frankton', 'Cambridge'],
        'description' => 'Beauty treatments, skincare, waxing, grooming, and personal care services.',
        'services' => ['Skincare', 'Waxing', 'Facials', 'Grooming'],
        'tags' => ['beauty', 'skin', 'facial', 'waxing'],
        'phone' => '021 999 777',
        'email' => 'beauty@example.com',
        'rating' => 4.7,
        'jobs_completed' => 96,
        'response_time' => 'Usually replies next business day',
    ],
    [
        'name' => 'Harbour Catering Co',
        'industry' => 'Food & Hospitality',
        'category' => 'Catering',
        'location' => 'Auckland',
        'service_areas' => ['Auckland Central', 'Newmarket', 'Parnell', 'North Shore', 'Manukau'],
        'description' => 'Catering and event hospitality for business meetings, private functions, birthdays, and small weddings.',
        'services' => ['Event catering', 'Corporate catering', 'Private functions', 'Finger food'],
        'tags' => ['catering', 'food', 'event', 'hospitality', 'corporate lunch'],
        'phone' => '021 345 678',
        'email' => 'catering@example.com',
        'rating' => 4.5,
        'jobs_completed' => 68,
        'response_time' => 'Usually replies same day',
    ],
    [
        'name' => 'NZ Digital Studio',
        'industry' => 'IT & Technology',
        'category' => 'Web Development',
        'location' => 'Auckland',
        'service_areas' => ['Auckland', 'Wellington', 'Christchurch', 'Remote'],
        'description' => 'Website design, Laravel development, web app support, IT setup, and digital solutions for small businesses.',
        'services' => ['Website design', 'Laravel development', 'Web app support', 'IT setup'],
        'tags' => ['web development', 'website', 'laravel', 'it support', 'software'],
        'phone' => '022 888 666',
        'email' => 'tech@example.com',
        'rating' => 4.8,
        'jobs_completed' => 84,
        'response_time' => 'Usually replies within 2 hours',
    ],
    [
        'name' => 'Harbour Accounting Services',
        'industry' => 'Professional Services',
        'category' => 'Accounting',
        'location' => 'Auckland',
        'service_areas' => ['Auckland', 'North Shore', 'Manukau', 'Remote'],
        'description' => 'Small business accounting, bookkeeping, GST, payroll, income tax, and Xero support.',
        'services' => ['Bookkeeping', 'GST returns', 'Payroll', 'Income tax', 'Xero support'],
        'tags' => ['accountant', 'accounting', 'gst', 'payroll', 'xero'],
        'phone' => '09 555 1234',
        'email' => 'accounting@example.com',
        'rating' => 4.6,
        'jobs_completed' => 148,
        'response_time' => 'Usually replies next business day',
    ],
];
